# Generated by Django 5.1.1 on 2024-10-08 11:32

import autoslug.fields
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=100)),
                ('features', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Dry cleaning', 'Dry cleaning'), ('Spa', 'Spa'), ('Gym', 'Gym'), ('Car park', 'Car park'), ('Wifi', 'Wifi'), ('Room service', 'Room service'), ('Special service', 'Special service')], max_length=200)),
                ('mobile_no', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('first_room_img', models.ImageField(upload_to='room_images')),
                ('second_room_img', models.ImageField(blank=True, null=True, upload_to='room_images')),
                ('third_room_img', models.ImageField(blank=True, null=True, upload_to='room_images')),
                ('price', models.IntegerField()),
                ('room_options', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wifi', 'Wifi'), ('Air Conditioning', 'Air Conditioning')], max_length=300)),
                ('is_Booked', models.BooleanField(blank=True, default=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
            ],
        ),
    ]
