# Generated by Django 5.1.1 on 2024-10-24 12:48

import autoslug.fields
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_remove_hotel_features_hotel_activities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('third_room_img', models.ImageField(blank=True, null=True, upload_to='room_images')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('room_options', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wifi', 'Wifi'), ('Air Conditioning', 'Air Conditioning')], max_length=300)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='room',
        ),
        migrations.RemoveField(
            model_name='room',
            name='first_room_img',
        ),
        migrations.RemoveField(
            model_name='room',
            name='second_room_img',
        ),
        migrations.RemoveField(
            model_name='room',
            name='third_room_img',
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_options',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Wifi', 'Wifi'), ('Air Conditioning', 'Air Conditioning'), ('TV', 'TV')], max_length=300),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='hotel.roomtype'),
        ),
    ]
