# Generated by Django 5.1.1 on 2024-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0009_alter_booking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked',
            field=models.BooleanField(default=False),
        ),
    ]
